### ISSUE TITLE
Template Not Found

### ISSUE THREAD

**Issue by MaximeRVY** [micimize/graphql-to-io-ts#3]
Hello, 

When I used the commands you specified in the Readme I've go an error: 

```
error: {"message":"Cannot find module 'graphql-to-io-ts'","stack":"Error: Cannot find module 'graphql-to-io-ts'\n    at Function.Module._resolveFilename (module.js:547:15)\n    at Function.Module._load (module.js:474:25)\n    at Module.require (module.js:596:17)\n    at require (internal/module.js:11:18)\n
```

To fix it, I have to go on my `node_modules/graphql-to-io-ts` folder and run `yarn build` to generate the dist folder.

Do you have any idea why ? 

Thanks

**Comment by micimize** [comment]
apologies, much to my chagrin I have apparently not been getting notifications from any of my projects for quite some time.

It's likely that this is due to this template being for an outdated version of `graphql-code-generator`. It will probably be some time before I have time to update it

**Comment by MaximeRVY** [comment]
Ok thanks for the info :-)
